Description of continenta
Home > Mfiles > continenta.m
continenta
PURPOSE
continenta.m from LATEX campaing
SYNOPSIS
This is a script file.
DESCRIPTION
 continenta.m from LATEX campaing
 Draw continents on a map
 Modified to work with coast files extracted from
 http://www.ngdc.noaa.gov/mgg/coast/
 Uses join_cst that uses fixcoast
campaign_coastline='strasse_coastline.txt';
CROSS-REFERENCE INFORMATION
This function calls:
join_cst JOIN_CST Makes continuous coastline from fragmented segments.
This function is called by:
plot_aviso This is an octave script used in cronjob_MODIS_AVISO.bsh
plot_aviso_old This is an octave script used in cronjob_MODIS_AVISO.bsh
SOURCE CODE
% continenta.m from LATEX campaing
%
% Draw continents on a map
%
% Modified to work with coast files extracted from
% http://www.ngdc.noaa.gov/mgg/coast/
%
% Uses join_cst that uses fixcoast
%campaign_coastline='strasse_coastline.txt';
campaign_coastline='outpace_coastline.txt';
raw_coast=load(campaign_coastline);
line0=join_cst(raw_coast,.0001);
k=[find(isnan(line0(:,1)))];
for i=1:length(k)-1,
    x=line0([k(i)+1:(k(i+1)-1)],1);
    y=line0([k(i)+1:(k(i+1)-1)],2);
    patch(x,y,[0.7,0.7,0.7]);
end;