Description of MAIN_modis
Home > Mfiles > MAIN_modis.m
MAIN_modis
PURPOSE
This is an octave script used in cronjob_MODIS_AVISO.bsh
SYNOPSIS
This is a script file.
DESCRIPTION
 This is an octave script used in cronjob_MODIS_AVISO.bsh
  to launch the analysis on the files previously downloaded
CROSS-REFERENCE INFORMATION
This function calls:
domain_limits Limits of domain
plot_modis
read_nc_modis Read Modis data from converted nc file
save_modis
This function is called by:
SOURCE CODE
% This is an octave script used in cronjob_MODIS_AVISO.bsh
%  to launch the analysis on the files previously downloaded
%-----------------------------------------------------------
% Cell array with arguments passed from bash script
 args=argv;
%
 Wrk_path=[args{1},'/'];
% mfiles_path=[args{2}];
 data_type=[args{3}]; % "for loop" for different data in cronjob_MODIS_AVISO.bsh
%-----------------------------------------------------------
%function MAIN_modis
%-----------------------------------------------------------
 %  % Uncomment this and comment above to test without need of bash script
 % %main_path='/media/DATA/STRASSE';
 % % Wrk_path='../Wrk/';
 %   Wrk_path='../../presentation_2072014/';
 % % data_type='CHL';
 % data_type='SST';
 %mfiles_path=[main_path,'/Mfiles/'];
%-----------------------------------------------------------
% Move to directory with octave scripts
%cd(mfiles_path)
% Read Lon Lat limit file
domain_limits
% use dir command to retrieve .nc file list
files=dir([Wrk_path,'*_',data_type,'*.nc']);
for i=1:length(files)
       disp(['%%%%%%%%%% ',files(i).name,' %%%%%%%%%%%%%%%%%%'])
       nc_name=files(i).name;
       nc_file=[Wrk_path,nc_name];
      % nc_file=[Wrk_path,'A2014049.L3m_DAY_CHL_chlor_a_4km.nc']
    disp(['   == Reading ==============================='])
    [lon lat var]=read_nc_modis(nc_file,Lat(2),Lat(1),Lon(1),Lon(2));
    day=nc_name(2:8);
%    day='2014049'; %test
    YY=day(1:4);
    doy=day(5:end);
    day=datestr(str2num(doy)+datenum([str2num(YY)-1 12 31]),'yyyymmdd');
    disp(['   == Plotting =============================='])
    plot_modis(Wrk_path,data_type,lon,lat,var,day);
    %plot_modis_territorial_water(Wrk_path,data_type,lon,lat,var,day);  % plot + territorial waters plot
    disp(['   == Saving .mat file ======================'])
    save_modis(Wrk_path,day,data_type,lon,lat,var)
end
% Message if no files found in Wrk
if length(files)==0
    disp(['   == No MODIS ',data_type,' processed !!!!! ========='])
end