Description of all_lagrangian_figs
Home > Mfiles > Lagrangian_package > all_lagrangian_figs.m
all_lagrangian_figs
PURPOSE
function all_lagrangian_figs(fname,product,out_path,ctday)
SYNOPSIS
This is a script file.
DESCRIPTION
function all_lagrangian_figs(fname,product,out_path,ctday)
 Modified from:
 $DATA/KEOPS2/octave/keops/analysis/realtime_cron/all_lagrangianfigs_keops2.m
 Create the figures using the all_lagrangian_diags mat file
CROSS-REFERENCE INFORMATION
This function calls:
continenta continenta.m from LATEX campaing
plusminusmap
strasse_boundary Limits of strasse campaign
This function is called by:
MAIN_Lagrangian ==============================================================================
SOURCE CODE
%function all_lagrangian_figs(fname,product,out_path,ctday)
% Modified from:
% $DATA/KEOPS2/octave/keops/analysis/realtime_cron/all_lagrangianfigs_keops2.m
%
% Create the figures using the all_lagrangian_diags mat file
%---------------------------------------------------------
% % Comment function line and uncomment below to test
% fname='/home/ENS/apogee/r1003867/Stage_OUTPACE/OUTPACE/Wrk/20140707_nrt_global_2014_d6.mat';
% product='nrt_global_2014';
% ctday=7;
% out_path='/home/ENS/apogee/r1003867/Stage_OUTPACE/OUTPACE/Wrk/';
%---------------------------------------------------------
%lvars=localvars;
if(~exist(fname,'file'))
    return;
end
load(fname);
% Label for figure title
titl=datestr(day0,1);
% lon lat matrices LR : Useless !!!
% lonvv=lonv(1):delta0:lonv(end);
%latvv=latv(1):delta0:latv(end);
%[long,latg]=meshgrid(lonvv,latvv);
% Labels for figures
lab_fig={'OW disp','OW param','FSLE','Lon adv','Lat adv','AVISO vel'};
%%%%%%%%%%%%%%%%%%%%%%%%
%       This command disable the output to the screen,
%       set it on 'on' if you want to see the figures before printing them!
 set (0, 'defaultfigurevisible', 'on');
 set (0,'defaultaxesfontsize',20)
 set (0,'defaulttextfontsize',30)
%%%%%%%%%%%%%%%%%%%%%%%%%%
%--- OW Dipsersion ----------------
%  nf=1; % Counter for figure and figure labels
%  figure(nf)
%  clf
%  imagesc(lonv,latv,OWdispersion_b,[0 60]);
%  axis xy
%  hold on
%  h=plot(lonsmowadv60(1:4:end,1:2:end),latsmowadv60(1:4:end,1:2:end),'m.');
%  set(h,'markersize',1);
%  % Set axis
%  %axis([lonv latv]);
%  axis([ton_zoom lat_zoom]);
%  % Draw coastline
%  continenta
%  % Draw strasse domain
%  strasse_boundary
%  line([Lon(1) Lon(1) Lon(2) Lon(2) Lon(1)], ...
%      [Lat(1) Lat(2) Lat(2) Lat(1) Lat(1)], ...
%      'color','g','linewidth',10)
%  % Title
%  title([lab_fig{nf},' ',titl],'fontsize',30);
%  % Set colorbar
%  H=colorbar;
 %--- OW parameter -----------------
 nf=2;
 figure(nf)
 clf
 %imagesc(lonv,latv,((60*60*24).^2)*owmi,[-1 1])
 imagesc(lonv,latv,((60*60*24).^2)*owmi,[-0.3 0.3])
 hold on
 grid on;
 % Flip axis
 axis xy
 axis([lonv latv]);
 %axis([lon_zoom lat_zoom]);
 % Draw coastline
  continenta %LR: à modifier avec les bonnes limites de la zone
 % Title
 title([lab_fig{nf},' ',titl],'fontsize',30);
 % Set colorbar
 colormap(plusminusmap);
 H=colorbar;
 % Print figure
 i=nf;
 Lab_Fig=strrep(lab_fig{i},' ','_');
 figname=sprintf('%s/%d%02d%02d_%s_d%s_%s.png',out_path,day0(1),day0(2),day0(3),product,num2str(ctday-1),Lab_Fig);
 figure(i);
 %print('-depsc',figname);
 disp('%------------------')
 disp(figname)
 disp('%------------------')
 print(i,[figname],'-dpng');
 close all
 %--- FLSLE ------------------------
 nf=3;
 figure(nf)
 clf
 imagesc(lonv,latv,-60*60*24*lambda,[0 .2])
 hold on
 grid on;
 % Flip axis
 axis xy
 axis([lonv latv]);
 %axis([lon_zoom lat_zoom]);
 % Draw coastline
 continenta
 % Draw strasse domain
 strasse_boundary
 line([Lon(1) Lon(1) Lon(2) Lon(2) Lon(1)], ...
     [Lat(1) Lat(2) Lat(2) Lat(1) Lat(1)], ...
     'color','m','linewidth',10)
 % Title
 title([lab_fig{nf},' ',titl],'fontsize',30);
 % Set colorbar
 colormap(plusminusmap);
 colorbar
 % Print figure
 i=nf;
 Lab_Fig=strrep(lab_fig{i},' ','_');
 figname=sprintf('%s/%d%02d%02d_%s_d%s_%s.png',out_path,day0(1),day0(2),day0(3),product,num2str(ctday-1),Lab_Fig);
 figure(i);
 %print('-depsc',figname);
 disp('%------------------')
 disp(figname)
 disp('%------------------')
 print(figname,'-dpng');
 close all
 %--- Lon Advection ----------------
 nf=4;
 figure(nf)
 clf
 imagesc(lonv,latv,lonf45,lonv-5)
 hold on
 grid on;
 % flip axis
 axis xy
 axis([lonv latv]);
 %axis([lon_zoom lat_zoom]);
 % Draw coastline
 continenta
 % Draw strasse domain
 strasse_boundary
 line([Lon(1) Lon(1) Lon(2) Lon(2) Lon(1)], ...
     [Lat(1) Lat(2) Lat(2) Lat(1) Lat(1)], ...
     'color','m','linewidth',10)
 % Title
 title([lab_fig{nf},' ',titl],'fontsize',30);
 % Set colorbar
 colormap(jet);
 colorbar
 % Print figure
 i=nf;
 Lab_Fig=strrep(lab_fig{i},' ','_');
 figname=sprintf('%s/%d%02d%02d_%s_d%s_%s.png',out_path,day0(1),day0(2),day0(3),product,num2str(ctday-1),Lab_Fig);
 figure(i);
 %print('-depsc',figname);
 disp('%------------------')
 disp(figname)
 disp('%------------------')
 print(figname,'-dpng');
 close all
 %--- Lat Advection ----------------
 nf=5;
 figure(nf)
 clf
 imagesc(lonv,latv,latf45,latv)
 hold on
 grid on;
 % Flip axis
 axis xy;
 axis([lonv latv]);
 %axis([lon_zoom lat_zoom]);
 % Draw coastline
 continenta
 % Draw strasse domain
 strasse_boundary
 line([Lon(1) Lon(1) Lon(2) Lon(2) Lon(1)], ...
     [Lat(1) Lat(2) Lat(2) Lat(1) Lat(1)], ...
     'color','m','linewidth',10)
 % Title
 title([lab_fig{nf},' ',titl],'fontsize',30);
 % Set colorbar
 colormap(jet);
 colorbar
 % Print figure
 i=nf;
 Lab_Fig=strrep(lab_fig{i},' ','_');
 figname=sprintf('%s/%d%02d%02d_%s_d%s_%s.png',out_path,day0(1),day0(2),day0(3),product,num2str(ctday-1),Lab_Fig);
 figure(i);
 %print('-depsc',figname);
 disp('%------------------')
 disp(figname)
 disp('%------------------')
 print(figname,'-dpng');
 close all
%--- AVISO velocities -------------
nf=6;
figure(nf)
clf
imagesc(lonv,latv,sqrt(Ucms.^2+Vcms.^2),[0 100])
hold on
grid on;
% Flip axis
axis xy
% Vector plot
sq=5;
h=quiver(lonvv(1:sq:end),latvv(1:sq:end),Ucms(1:sq:end,1:sq:end),Vcms(1:sq:end,1:sq:end),3);
set(h,'color','w');
% Draw coastline
continenta
hi=quiver(148,-28,1,0,3);
set(hi,'color','k');
text(148,-29,'m/s','Fontsize',10);
% % Title
title([lab_fig{nf},' ',titl],'fontsize',30);
% Set colorbar
colormap(jet);
colorbar
% Print figure
i=nf;
Lab_Fig=strrep(lab_fig{i},' ','_');
figname=sprintf('%s/%d%02d%02d_%s_d%s_%s.png',out_path,day0(1),day0(2),day0(3),product,num2str(ctday-1),Lab_Fig);
figure(i);
%print('-depsc',figname);
disp('%------------------')
disp(figname)
disp('%------------------')
print(figname,'-dpng');
close all
%  % for i=1:nf
%  for i=2:nf
%      Lab_Fig=strrep(lab_fig{i},' ','_');
%      figname=sprintf('%s/%d%02d%02d_%s_d%s_%s.png',out_path,day0(1),day0(2),day0(3),product,num2str(ctday-1),Lab_Fig);
%      figure(i);
%      %print('-depsc',figname);
%      disp('%------------------')
%      disp(figname)
%      disp('%------------------')
%      print(figname,'-dpng');
%  end