Description of localvars
Home > Mfiles > Lagrangian_package > localvars.m
localvars
PURPOSE
Previously defined in MAIN_Lagrangian.m
SYNOPSIS
function lvars=localvars
DESCRIPTION
 Previously defined in MAIN_Lagrangian.m
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
MAIN_Lagrangian ==============================================================================
getncUV_nrt_global_2010
getncUV_nrt_global_2014
getncUV_upd_global_2010
getncUV_upd_global_2014
SOURCE CODE
function lvars=localvars
% Previously defined in MAIN_Lagrangian.m
global DATADIR
global LAMTADIR
lvars.datadir=DATADIR;
lvars.lamtadir=LAMTADIR;